import { Inter, Roboto_Condensed, Noto_Serif} from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const robotoCondensed = Roboto_Condensed({ subsets: ["latin"] });
const notoSerif = Noto_Serif({subsets: ["latin"], weight: ['400']})

export const metadata = {
  title: "Cormac McCann | Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${robotoCondensed.className}`}>
        <Nav/>
        <div className="hidden md:block aura aura--blue" />
        <div className="hidden md:block aura aura--nova" />
        <div className="relative z-10">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
