import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Navigation from "./Navigation";

const inter = Montserrat({ subsets: [] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Navigation />
      <body className={inter.className}>
        {/* <Navigation /> */}
        {children}
      </body>
    </html>
  );
}
